# Generated by Django 5.0.1 on 2024-02-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study_app', '0004_crescentlib_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crescentlib',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
