# Generated by Django 5.0.2 on 2024-02-17 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study_app', '0005_alter_crescentlib_read'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crescentlib',
            options={'ordering': ['id']},
        ),
    ]
